### PR TITLE
Fix positional arguments when calling function with arguments

### PR DESCRIPTION
**Pull request by snacsnoc**
Use position arguments instead of keyword arguments, fixes passing variables.

Example output of `main.py` from the cpp example in this repo:
```
from sushipy.execute import Execute
def helloWorld(number):	Execute('main.hpp', number)
```

Fixes issue #15

### CODE REVIEW

**Comment by ksawery29** [comment]
Thanks for the pull request! I will look into this later

**Review by ksawery29 — APPROVED** [review]
Looks good! Thanks for another awesome pull request!

**Comment by ksawery29** [comment]
@snacsnoc I know it's an old pull request, but I think you forgot to remove from here kwargs.
```py
file_name = main_config["lib_path"].replace("*", kwargs.get("file"))
```

Strange I found it that late.

**Comment by ksawery29** [comment]
After fixing this pytest is now returning some errors (see #23)
I will try to fix it later today or tomorow.

**Comment by snacsnoc** [comment]
@ksawery29  Got it, I'll look into the errors and try to fix as well

**Pull request merged**
