### PR TITLE
Add verbose mode

### PR DESCRIPTION
**Pull request by snacsnoc**
This PR adds verbose printing for debugging purposes to sushi. The goal of this pull request is to increase the visibility of the workings of sushi when processing foreign language files. This address issues #21 

`rich_print()` has been moved to `utils/verbose_print` and is controlled by a boolean flag.

Users can enable the verbose flag by modifying their sushi.conf file. Example:
```
[main]
lang = h
lib_path = lib/main.h

[launch]
exec_command = gcc -o lib/out [file-name]
import_syntax = #include "[file-name]"
verbose = yes
```

### CODE REVIEW

**Comment by snacsnoc** [comment]
Current output example:
Screenshot 2023-03-17 at 19 19 06

**Comment by snacsnoc** [comment]
@ksawery29 Thanks for moving `verbose_flag` config check to `utils/verbose_print`, that makes much more sense.

What else needs to be done? I think the only code missing verbose print is the Cache

**Comment by ksawery29** [comment]
@snacsnoc I added verbose print for config extends but once again tests are failing 🙄 
I think we should in future rewrite tests to make sure they don't fail this often.

**Comment by snacsnoc** [comment]
@ksawery29 I agree, the tests need to be rewritten. I can take a crack at the tests in the next day or two. 

Would you prefer to have working tests before this PR is merged?

**Comment by ksawery29** [comment]
@snacsnoc

Yeah we could fix the tests before merging this PR. 
I will also take a look into this tests tomorrow. Thanks for the help!

**Comment by ksawery29** [comment]
@snacsnoc I think we should merge it now just to make creating new tests easier.

**Comment by snacsnoc** [comment]
@ksawery29 Haha I'd have to agree, the verbose mode will make debugging easier.

**Review by ksawery29 — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
