### PR TITLE
Fix Pytest testing

### PR DESCRIPTION
**Pull request by snacsnoc**
This PR aims to simplify the Pytest and ensure it runs successfully for future sushi builds. Errors are generated from the Github Action and this PR hopes to solve that.

### CODE REVIEW

**Comment by ksawery29** [comment]
@snacsnoc 
I think it looks good now. What needs to be done?

**Comment by snacsnoc** [comment]
@ksawery29 I have some hesitancy if it will work with Github Actions since it still has the same `assert` statement.

**Comment by ksawery29** [comment]
@snacsnoc any updates? Is it ready for review?

**Comment by snacsnoc** [comment]
Hello, sorry I have been busy with work. Are we able to determine why the
GHA pytests fail? Is it perhaps path related?

**Comment by ksawery29** [comment]
@snacsnoc I think I will change the pull request to ready for review because it seems the issue is fixed now. If it will still fail we can create another pull request.

**Review by ksawery29 — APPROVED** [review]

**Comment by ksawery29** [comment]
Strange that it's still failing. Any ideas @snacsnoc? It works on your fork.

**Pull request merged**
